### PR TITLE
feat: resolve Lighthouse a11y warnings from the button element

### LINKED ISSUE #13: Accessibility changes for the color mode toggle: aria support and unhide
Hi 👋🏼 I use your version of the react-dark-mode-toggle on my personal blog and it's really great, thank you for creating and sharing it!

With [Lighthouse](https://github.com/GoogleChrome/lighthouse) and [WAVE Web Accessibility Evaluation Tools](https://wave.webaim.org/) I've identified the following issues impacting my reports.

1. aria-hidden is set on a focusable element. In order to meet the [WCAG AA aria-hidden-focus rule](https://dequeuniversity.com/rules/axe/4.0/aria-hidden-focus), this element must not be hidden.
2. The button has no discernible text. In order to meet the [WCAG A button-name rule](https://dequeuniversity.com/rules/axe/4.4/button-name), a button must contain a text or label.

Because of these warnings, and because people rely on assistive technology for a range of conditions and may still wish or even need to toggle the color mode, I propose removing `aria-hidden` and allowing consumers set an `aria-label` on the button element. The way I've done that in my implementation is with a new, optional `attributes` prop that gets spread onto the button element. That allows consumers to optionally pass in attributes like `aria-label`, `aria-labelledby`, `aria-hidden` if they wish to use the old behavior, or even `data-testid` and other attributes.

I'm going to open a PR with changes I have in a fork at chrisvogt/react-dark-mode-toggle-2@094fc96a8c7cdcf63cba56722b1031141a219de5, and I'm happy to modify it to use an alternative approach if you prefer a different implementation!

I've deployed this change to my website via chrisvogt/gatsby-theme-chrisvogt#180 and it improved my Lighthouse accessibility score by

### PR DESCRIPTION
**Pull request by chrisvogt**
This PR closes #13 by implementing the following changes.

1. It removes the `aria-hidden` attribute from the button element, resolving the [aria-hidden-focus](https://rocketvalidator.com/accessibility-validation/axe/4.9/aria-hidden-focus) failure I'm getting in accessibility reports.
2. It adds support for optional, custom attributes that can be set on the button element. These can be used to set an `aria-label` to resolve the [button-name](https://dequeuniversity.com/rules/axe/4.4/button-name) failure I'm getting in accessibility reports. They can also be used to set attributes like `data-testid` or `data-cy` for test runners.

These changes improved my Lighthouse accessibility score by 7 points. Let me know if you'd prefer to this implemented in a different way, or if you have anything else you'd like done before merging!

> [!NOTE]
> I had some trouble getting Storybook to run in my local development setup. Have you ever seen **Error [ERR_REQUIRE_ESM]: require() of ES Module not supported.** when running Storybook?

### CODE REVIEW

**Comment by trevorlasn** [comment]
@todd-elvers

**Comment by chrisvogt** [comment]
Thanks @indreklasn. I've been using my fork on my personal website since I posted this, but would much rather use the original package!

Here's an example showing how I install the forked package if you want to test it out.

https://github.com/chrisvogt/gatsby-theme-chrisvogt/blob/90492e5b4fb28bb7fa1655d8a187efdb97d2f1ae/theme/package.json#L100

**Comment by trevorlasn** [comment]
@chrisvogt Good idea. Any chance of fixing the error too?

```js
Warning: Unknown: Support for defaultProps will be removed from memo components in a future major release. Use JavaScript default parameters instead. Error Component Stack
```

Lighthouse issue:

Screenshot 2024-10-28 at 10 22 59

**Comment by trevorlasn** [comment]
@chrisvogt @todd-elvers any updates?

**Comment by todd-elvers** [comment]
@chrisvogt @indreklasn Updates look good!  I appreciate your efforts here.

**Pull request merged**
