### PR TITLE
Allow any attribute like "id", "data-tid" ,... for testing purpose

### PR DESCRIPTION
**Pull request by coolusaHD**
This PR allows user to use any attribute they want so they can add things like `id` ,`data-tid`, etc.

Thanks in advance 😄

### CODE REVIEW

**Comment by todd-elvers** [comment]
Nice, I'll take a look at this and try to merge it tomorrow!

**Comment by coolusaHD** [comment]
That would be awesome.
With this update it should be possible (for me) to test the behaviour of the dark mode toggle in my project 👍

**Comment by todd-elvers** [comment]
@coolusaHD I reviewed your changes and there are a couple of issues.

### Small Code Issue
You updated the props declaration but didn't update the actual component to use these new props.  So you'd likely need to update the component declaration so that all "extra props" are de-structured into something like `extraProps` or `rest` or something and then explode them into the `button` component that contains the toggle.

### Larger TypeScript Issue
Because `any` effectively tells TypeScript to disable type-checking, adding a `[key: string]: any` to the props declaration disabled type-checking and allows bogus props like `todd={true}` to be passed in.  

I even tried something a little more strict like:
```
type Props = React.HTMLAttributes<HTMLButtonElement> & {
  ...
}
```

But that is also a bit confusing as it allows the user to pass in a lot of values that we do not handle (e.g. `OnDragExit` or `spellCheck`).

### Conclusion
If you _really_ need this functionality I would recommend reworking this PR to specify only the attributes you need.

However if you're adding this functionality so that you can:
- Target the component with styles
- Locate the component within a test

then I would say this is probably overkill.  You can already pass in a `className` prop that gets applied to the underlying `button` and/or wrap the toggle in a separate component with a specific `data-testid` attribute.

Apologies if I'm misunderstanding the purpose of these changes, please correct me if I am.

**Comment by coolusaHD** [comment]
I see...
I think adding the prop `id` would be enough as the most test systems allow queries by id's.
I will rework the PR :)

**Comment by coolusaHD** [comment]
I see...
I think adding the prop `id` would be enough as the most test systems allow queries by id's.
I will rework the PR :)

**Comment by coolusaHD** [comment]
@todd-elvers 
I changed it to only allow the id prop.
I've added it to the template and hopefully correct to the other parts of the package.
Please have a look and correct me if I forget something.

Before you merge I can also modify the README if you want 👍

**Comment by coolusaHD** [comment]
@todd-elvers ping

**Comment by todd-elvers** [comment]
@coolusaHD Thank you for pinging me!  I'll review this tomorrow morning and try to get it merged!

**Comment by todd-elvers** [comment]
Look at the code now!  Probably merging in a few minutes.

**Review by todd-elvers — APPROVED** [review]
Great work!  LGTM!

**Pull request merged**
